apiVersion: apps/v1
kind: Deployment
ametadata:
 name: hello
 labels:
  app: hello
spec:
 selector:
    matchLabels:
      app: hello
 strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
template:
  metadata:
   labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: kiranug/hello:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
  namespace: default
spec:
  ports:
  - nodePort: 31664
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
  sessionAffinity: None
  type: LoadBalancer
